version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8001:8001
    depends_on:
      - web
    networks:
      - main
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static
      - media_volume:/app/images
  web:
    build: .
    env_file: .env
    command: gunicorn bookwyrm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/images
      - /run/postgresql:/run/postgresql
      - /run/redis/redis.sock:/run/redis/redis.sock
    depends_on:
      - celery_worker
    networks:
      - main
    ports:
      - 8000:8000
  celery_worker:
    env_file: .env
    build: .
    networks:
      - main
    command: celery -A celerywyrm worker -l info -Q high_priority,medium_priority,low_priority
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/images
      - /run/postgresql:/run/postgresql
      - /run/redis/redis.sock:/run/redis/redis.sock
    restart: on-failure
  flower:
    build: .
    command: celery -A celerywyrm flower
    env_file: .env
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    volumes:
      - .:/app
      - /run/redis/redis.sock:/run/redis/redis.sock
    networks:
      - main
    restart: on-failure
volumes:
  static_volume:
  media_volume:
networks:
  main:
